name: Py4Eng
dependencies:
- bzip2=1.0.6
- cycler=0.9.0
- cython=0.24
- decorator=4.0.9
- fastcache=1.0.2
- freetype=2.5.5
- ipykernel=4.2.2
- ipyparallel=5.0.1
- ipython=4.1.1
- ipython_genutils=0.1.0
- ipywidgets=4.1.1
- jinja2=2.8
- jpeg=8d
- jsonschema=2.4.0
- jupyter=1.0.0
- jupyter_client=4.1.1
- jupyter_console=4.1.0
- jupyter_core=4.0.6
- libpng=1.6.17
- libtiff=4.0.6
- markupsafe=0.23
- matplotlib=1.5.1
- mistune=0.7.1
- mkl=11.3.1
- nbconvert=4.1.0
- nbformat=4.0.1
- networkx=1.11
- notebook=4.1.0
- numpy=1.10.4
- pandas=0.17.1
- path.py=8.1.2
- pickleshare=0.5
- pillow=3.1.1
- pip=8.0.3
- psutil=4.0.0
- pygments=2.1.1
- pyparsing=2.0.3
- pyqt=4.11.4
- python=3.5.1
- python-dateutil=2.4.2
- pytz=2015.7
- pyzmq=15.2.0
- qt=4.8.7
- qtconsole=4.1.1
- requests=2.9.1
- scikit-image=0.11.3
- scikit-learn=0.17.1
- scipy=0.17.0
- seaborn=0.7.0
- setuptools=20.6.7
- simplegeneric=0.8.1
- sip=4.16.9
- six=1.10.0
- sympy=0.7.6.1
- tk=8.5.18
- tornado=4.3
- traitlets=4.1.0
- wheel=0.29.0
- zlib=1.2.8
- pip:
  - aiohttp==0.21.2
  - apscheduler==3.0.5
  - argh==0.26.1
  - babel==2.2.0
  - basemap==1.0.8
  - chardet==2.3.0
  - delorean==0.6.0
  - humanize==0.5.1
  - ipdb==0.8.1
  - ipython-genutils==0.1.0
  - ipython-memory-usage==1.0
  - jupyter-client==4.1.1
  - jupyter-console==4.1.0
  - jupyter-core==4.0.6
  - memory-profiler==0.41
  - pathtools==0.1.2
  - pyyaml==3.11
  - sdeint==0.2.1.dev0
  - sphinx==1.3.1
  - toolz==0.7.4
  - tzlocal==1.2.2
  - watchdog==0.8.3

