name: Py4Eng
dependencies:
- click
- cython
- flask=0.10
- ipykernel
- ipython
- ipywidgets
- jupyter
- matplotlib=1.5
- notebook
- numba
- numpy
- pandas
- pillow
- pip
- python=3.5
- requests
- scikit-image
- scikit-learn
- scipy
- seaborn
- sympy
- pip:
  - ipdb
  - pygubu
  - sdeint