name: Py4Eng
dependencies:
- cartopy
- click
- cython
- flask
- ipdb
- ipykernel
- ipywidgets
- jupyter
- matplotlib
- notebook
- numba
- numpy
- pandas
- pip
- python=3.6
- requests
- scikit-image
- scikit-learn
- scipy
- seaborn
- sympy
- statsmodels
- tensorflow
- pip:
  - pygubu
  - sdeint