name: Py4Eng
dependencies:
- backports.shutil_get_terminal_size=1.0.0
- basemap=1.0.8.dev0
- blas=1.1
- click=6.6
- cycler=0.10.0
- cython=0.24
- decorator=4.0.9
- entrypoints=0.2.1
- fastcache=1.0.2
- flask=0.10.1
- fontconfig=2.11.1
- freetype=2.6.3
- geos=3.4.2
- icu=56.1
- ipykernel=4.3.1
- ipython=4.2.0
- ipython_genutils=0.1.0
- ipywidgets=5.1.5
- itsdangerous=0.24
- jinja2=2.8
- jpeg=9b
- jsonschema=2.5.1
- jupyter=1.0.0
- jupyter_client=4.2.2
- jupyter_console=4.1.1
- jupyter_core=4.1.0
- libgcc=5.2.0
- libiconv=1.14
- libpng=1.6.22
- libsodium=1.0.10
- libtiff=4.0.6
- libxml2=2.9.3
- llvmlite=0.11.0
- markupsafe=0.23
- matplotlib=1.5.1
- mistune=0.7.2
- mkl=11.3.3
- mpmath=0.19
- nbconvert=4.2.0
- nbformat=4.0.1
- ncurses=5.9
- networkx=1.11
- notebook=4.2.0
- numba=0.26.0
- numpy=1.11.0
- openblas=0.2.18
- openssl=1.0.2h
- pandas=0.18.1
- pexpect=4.1.0
- pickleshare=0.7.2
- pillow=3.2.0
- pip=8.1.1
- protobuf=3.0.0b2
- ptyprocess=0.5.1
- pygments=2.1.3
- pyparsing=2.1.4
- pyproj=1.9.5.1
- pyqt=4.11.4
- pyshp=1.2.3
- python=3.5.1
- python-dateutil=2.5.3
- python-simplegeneric=0.8.1
- pytz=2016.4
- pyzmq=15.2.0
- qt=4.8.7
- qtconsole=4.2.1
- readline=6.2
- requests=2.10.0
- scikit-image=0.12.3
- scikit-learn=0.17.1
- scipy=0.17.1
- seaborn=0.7.0
- setuptools=21.2.1
- sip=4.16.9
- six=1.10.0
- sqlite=3.9.2
- sympy=1.0
- tensorflow=0.8.0
- terminado=0.6
- tk=8.5.18
- tornado=4.3
- traitlets=4.2.1
- werkzeug=0.11.9
- wheel=0.29.0
- widgetsnbextension=1.2.3
- xz=5.0.5
- zeromq=4.1.4
- zlib=1.2.8
- pip:
  - appdirs==1.4.0
  - backports.shutil-get-terminal-size==1.0.0
  - ipdb==0.10.0
  - ipython-genutils==0.1.0
  - jupyter-client==4.2.2
  - jupyter-console==4.1.1
  - jupyter-core==4.1.0
  - pygubu==0.9.7.8
  - sdeint==0.2.0
  - simplegeneric==0.8.1

